import{S as L,i as c,a as p}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const v=document.querySelector(".form"),u=document.querySelector(".gallery");document.querySelector(".gallery-box");const i=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom");document.querySelector("input");const n=document.querySelector(".load-image");document.querySelector("body");const S="41767782-13727767f44f3e84ebf7a04b0",q="https://pixabay.com";let a=1,d="sun",f=40;const g=new L(".gallery a",{nav:!0,captionDelay:300,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});v.addEventListener("submit",w);n.addEventListener("click",x);async function w(s){if(s.preventDefault(),i.style.display="block",n.style.display="none",a=1,d=s.target.elements.search.value.trim(),!d){u.innerHTML="",c.info({position:"bottomRight",message:"Error enter any symbols"}),i.style.display="none";return}try{const{data:{hits:r,totalHits:t}}=await h(d,a);r.length>0?(i.style.display="none",u.innerHTML=b(r),g.refresh(),c.success({position:"bottomRight",message:`We found ${t} photos`}),n.style.display="block"):(u.innerHTML="",c.error({position:"bottomRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(n.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",s.target.reset()}}function h(s,r){return p.defaults.baseURL=q,p.get("/api/",{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function b(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function x(s){m.style.display="block",n.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{a+=1;const{data:{hits:l,totalHits:e}}=await h(d,a),o=Math.ceil(e/f);if(n.style.display="block",u.insertAdjacentHTML("beforeend",b(l)),g.refresh(),a===o)return n.style.display="none",c.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
